# Generated by Django 3.1.7 on 2021-02-28 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(help_text='Organisation used after @', max_length=30)),
                ('world', models.CharField(blank=True, help_text='if not set, will be added from request to map_url', max_length=30, null=True)),
                ('room', models.CharField(blank=True, help_text='if not set, will be added from request to map_url', max_length=30, null=True)),
                ('map_url', models.URLField()),
                ('policy', models.IntegerField(choices=[(1, 'Anonymous'), (2, 'Members only'), (3, 'use Tags')])),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='wa_organization',
            field=models.CharField(default='cybercamp', help_text='OrganisationSlug, for start map', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='wa_room',
            field=models.CharField(default='map.json', help_text='RoomSlug, for start map', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='wa_uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wa_world',
            field=models.CharField(default='camp', help_text='WorldSlug, for start map', max_length=30),
        ),
    ]
