# Generated by Django 3.1.7 on 2021-05-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wa_room',
            field=models.CharField(default='basemap.json', help_text='RoomSlug, for start map', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='wa_world',
            field=models.CharField(default='eulenspiegel', help_text='WorldSlug, for start map', max_length=30),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='end_time',
            field=models.DateTimeField(help_text='Bis wann geht dein Workshop?', verbose_name='Bis'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='start_time',
            field=models.DateTimeField(help_text='Wann beginnt dein Workshop?', verbose_name='Von'),
        ),
    ]
